# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = Rails.application.credentials.dig(Rails.env.to_sym, :MAILJET_API_KEY)
  config.secret_key = Rails.application.credentials.dig(Rails.env.to_sym, :MAILJET_SECRET_KEY)
  config.api_version = "v3.1"
end
