default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  user: <%= Rails.application.credentials.dig(:pg, :name) %>
  password: <%= Rails.application.credentials.dig(:pg, :password) %>
  database: <%= Rails.application.credentials.dig(:pg, :db) %>
